//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeronave
    {
        public int id_aeronave { get; set; }
        public int id_modelo { get; set; }
        public int id_fabricante { get; set; }
        public string id_companhia { get; set; }
        public string cor { get; set; }
        public string descricao { get; set; }
        public byte[] som { get; set; }
        public byte[] foto { get; set; }
    }
}
