//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirSystemContainer : DbContext
    {
        public AirSystemContainer()
            : base("name=AirSystemContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fabricante> Fabricante { get; set; }
        public virtual DbSet<Aeronave> Aeronave { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<Companhia> Companhia { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
