//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companhia
    {
        public int id_companhia { get; set; }
        public string companhia { get; set; }
        public string cnpj { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public byte[] foto { get; set; }
    }
}
