//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fabricante
    {
        public int id_fabricante { get; set; }
        public string nome { get; set; }
        public string sede { get; set; }
        public string pais_origem { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
    }
}
