//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public int id_modelo { get; set; }
        public string modelo { get; set; }
        public int qtd_assento { get; set; }
        public string origem { get; set; }
        public string fabricacao { get; set; }
        public string turbinas { get; set; }
    }
}
