//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int id_usuario { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public string endereco { get; set; }
        public string nascimento { get; set; }
        public string numero { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
        public byte[] foto { get; set; }
        public string tipo_usuario { get; set; }
    }
}
